// Auto-generated by PoolConfigScriptableObjectInspector — do not edit manually
// Re-generate from PoolConfig.asset Inspector

namespace NuoYan.Pool.GameObjectPool
{
    public static class PoolItemConstants
    {
        public const string EntityComponent = "EntityComponent";
        public const string MapLine = "MapLine";
        public const string Node = "Node";
    }
}
